<a href="https://colab.research.google.com/github/Seoyoung-Kim-Meister/analysis_Galaxus/blob/main/EY_Hackathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt


from google.colab import drive
drive.mount('/content/EY.xlsx')

Drive already mounted at /content/EY.xlsx; to attempt to forcibly remount, call drive.mount("/content/EY.xlsx", force_remount=True).

In [95]:
import pandas as pd

df = pd.read_excel('/content/EY.xlsx/MyDrive/EY.xlsx')
display(df.head())

,id,first_name,last_name,birthdate,gender,zipcode,city,canton,income_monthly_chf,number_of_children,number_of_adults,has_job,available_for_job,job_looking_start,job_looking_end,Unnamed: 15
0,1,Dominic,Dubs,01.01.1764,2.0,1400,Yverdon-Les-Bains,Switzerland,13355.0,1.0,2.0,0,0.0,2023-04-10,2025-07-14,NaN
1,2,Ziegler,Jaspersen,01.01.1764,2.0,5210,Windisch,Aargau,4658.0,0.0,2.0,1,NaN,2023-04-14,2025-07-20,NaN
2,3,Hansrudolf,Schneebeli,01.01.1764,2.0,5512,Wohlenschwil,Aargau,7511.0,2.0,1.0,0,0.0,2023-04-11,2025-07-20,NaN
3,4,Linus,ROUMPIES,01.01.1764,1.0,1400,Yverdon-Les-Bains,Vaud,3896.0,3.0,2.0,1,NaN,2023-04-18,2025-07-22,NaN
4,5,Raphael,Schmid-Weibel,01.01.1764,2.0,8422,Pfungen,Switzerland,17346.0,1.0,1.0,0,1.0,2023-04-18,2025-07-22,Dummy Data Set:\nTest purpose only

In [96]:
df['birthdate'] = pd.to_datetime(df['birthdate'], format='%d.%m.%Y', errors='coerce')
df['birthdate'] = df['birthdate'].dt.year.astype('Int64')
display(df.head())

,id,first_name,last_name,birthdate,gender,zipcode,city,canton,income_monthly_chf,number_of_children,number_of_adults,has_job,available_for_job,job_looking_start,job_looking_end,Unnamed: 15
0,1,Dominic,Dubs,1764,2.0,1400,Yverdon-Les-Bains,Switzerland,13355.0,1.0,2.0,0,0.0,2023-04-10,2025-07-14,NaN
1,2,Ziegler,Jaspersen,1764,2.0,5210,Windisch,Aargau,4658.0,0.0,2.0,1,NaN,2023-04-14,2025-07-20,NaN
2,3,Hansrudolf,Schneebeli,1764,2.0,5512,Wohlenschwil,Aargau,7511.0,2.0,1.0,0,0.0,2023-04-11,2025-07-20,NaN
3,4,Linus,ROUMPIES,1764,1.0,1400,Yverdon-Les-Bains,Vaud,3896.0,3.0,2.0,1,NaN,2023-04-18,2025-07-22,NaN
4,5,Raphael,Schmid-Weibel,1764,2.0,8422,Pfungen,Switzerland,17346.0,1.0,1.0,0,1.0,2023-04-18,2025-07-22,Dummy Data Set:\nTest purpose only

In [97]:
df

,id,first_name,last_name,birthdate,gender,zipcode,city,canton,income_monthly_chf,number_of_children,number_of_adults,has_job,available_for_job,job_looking_start,job_looking_end,Unnamed: 15
0,1,Dominic,Dubs,1764,2.0,1400,Yverdon-Les-Bains,Switzerland,13355.0,1.0,2.0,0,0.0,2023-04-10,2025-07-14,NaN
1,2,Ziegler,Jaspersen,1764,2.0,5210,Windisch,Aargau,4658.0,0.0,2.0,1,NaN,2023-04-14,2025-07-20,NaN
2,3,Hansrudolf,Schneebeli,1764,2.0,5512,Wohlenschwil,Aargau,7511.0,2.0,1.0,0,0.0,2023-04-11,2025-07-20,NaN
3,4,Linus,ROUMPIES,1764,1.0,1400,Yverdon-Les-Bains,Vaud,3896.0,3.0,2.0,1,NaN,2023-04-18,2025-07-22,NaN
4,5,Raphael,Schmid-Weibel,1764,2.0,8422,Pfungen,Switzerland,17346.0,1.0,1.0,0,1.0,2023-04-18,2025-07-22,Dummy Data Set:\nTest purpose only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11207,11208,Aissa,Stress,1993,2.0,8400,Winterthur,Zürich,13214.0,2.0,2.0,0,0.0,2023-04-30,2025-09-29,NaN
11208,11209,Ladan,Streuli,1993,2.0,8400,Winterthur,Zürich,17715.0,2.0,2.0,0,0.0,2023-04-23,2025-10-24,NaN
11209,11210,Andrea,Stroitz,1993,1.0,8636,Wald ZH,Zürich,1595.0,2.0,1.0,0,0.0,2023-05-03,10010-12-31,NaN
11210,11211,Nicole,Strunck,1996,1.0,1167,Lussy-sur-Morges,Vaud,15869.0,3.0,1.0,0,0.0,2023-05-08,10010-12-31,NaN
11211,11212,Lia,Stückelberger,1998,1.0,6600,Locarno,Ticino,14821.0,2.0,2.0,0,0.0,2023-04-14,10010-12-31,NaN

In [98]:
df.dropna(subset=['birthdate'], inplace=True)
display(df.head())

,id,first_name,last_name,birthdate,gender,zipcode,city,canton,income_monthly_chf,number_of_children,number_of_adults,has_job,available_for_job,job_looking_start,job_looking_end,Unnamed: 15
0,1,Dominic,Dubs,1764,2.0,1400,Yverdon-Les-Bains,Switzerland,13355.0,1.0,2.0,0,0.0,2023-04-10,2025-07-14,NaN
1,2,Ziegler,Jaspersen,1764,2.0,5210,Windisch,Aargau,4658.0,0.0,2.0,1,NaN,2023-04-14,2025-07-20,NaN
2,3,Hansrudolf,Schneebeli,1764,2.0,5512,Wohlenschwil,Aargau,7511.0,2.0,1.0,0,0.0,2023-04-11,2025-07-20,NaN
3,4,Linus,ROUMPIES,1764,1.0,1400,Yverdon-Les-Bains,Vaud,3896.0,3.0,2.0,1,NaN,2023-04-18,2025-07-22,NaN
4,5,Raphael,Schmid-Weibel,1764,2.0,8422,Pfungen,Switzerland,17346.0,1.0,1.0,0,1.0,2023-04-18,2025-07-22,Dummy Data Set:\nTest purpose only

In [99]:
df.shape

(11119, 16)

In [100]:
df = df[(df['birthdate'] >= 1951) & (df['birthdate'] <= 2010)]
display(df.head())

,id,first_name,last_name,birthdate,gender,zipcode,city,canton,income_monthly_chf,number_of_children,number_of_adults,has_job,available_for_job,job_looking_start,job_looking_end,Unnamed: 15
577,578,Walker,Jauregui Estrada,1951,1.0,1700,Fribourg,Fribourg / Freiburg,14361.0,2.0,1.0,0,0.0,2023-04-18,10010-12-31,NaN
578,579,Silvia,Liechti - Senior,1952,1.0,8266,Steckborn,Thurgau,7448.0,2.0,1.0,0,0.0,2023-05-02,10010-12-31,NaN
579,580,Marcel,Rebelo Rodrigues,1953,1.0,4125,Riehen,Basel-Stadt,16757.0,0.0,1.0,0,1.0,2023-04-30,2025-09-08,NaN
580,581,Slawomir Janusz,Gautschi,1953,1.0,4125,Riehen,Basel-Stadt,13580.0,2.0,2.0,0,0.0,2023-04-24,10010-12-31,NaN
581,582,Rolf,Ghouzlaoui,1953,1.0,8006,Zürich,Zürich,3467.0,1.0,2.0,0,0.0,2023-04-14,10010-12-31,NaN

In [101]:
cantons_to_drop = ['Hong Kong', 'Austria', 'Italy', 'Liechtenstein', 'Nigeria', 'Germany', 'France']
df = df[~df['canton'].isin(cantons_to_drop)]

In [102]:
df.shape

(9377, 16)

In [103]:
df_clean = df[(df['canton'] != 'Switzerland')]
df_canton_switzerland = df[(df['canton'] == 'Switzerland')]

(897, 16)

In [104]:
df_clean.shape
df_canton_switzerland.shape

(897, 16)

In [106]:
df_no_job_clean = df_clean[(df_clean['has_job'] ==0)]
df_yes_job_clean = df_clean[(df_clean['has_job'] ==1)]
df_no_job_switzerland = df_canton_switzerland[(df_canton_switzerland['has_job'] ==0)]
df_yes_job_switzerland = df_canton_switzerland[(df_canton_switzerland['has_job'] ==1)]

In [107]:
df_no_job_clean.shape

(6580, 16)

In [108]:
df_yes_job_clean.shape

(1900, 16)

In [109]:
df_no_job_switzerland.shape

(667, 16)

In [110]:
df_yes_job_switzerland.shape

(230, 16)

In [111]:
df_no_job_clean

,id,first_name,last_name,birthdate,gender,zipcode,city,canton,income_monthly_chf,number_of_children,number_of_adults,has_job,available_for_job,job_looking_start,job_looking_end,Unnamed: 15
577,578,Walker,Jauregui Estrada,1951,1.0,1700,Fribourg,Fribourg / Freiburg,14361.0,2.0,1.0,0,0.0,2023-04-18,10010-12-31,NaN
578,579,Silvia,Liechti - Senior,1952,1.0,8266,Steckborn,Thurgau,7448.0,2.0,1.0,0,0.0,2023-05-02,10010-12-31,NaN
579,580,Marcel,Rebelo Rodrigues,1953,1.0,4125,Riehen,Basel-Stadt,16757.0,0.0,1.0,0,1.0,2023-04-30,2025-09-08,NaN
580,581,Slawomir Janusz,Gautschi,1953,1.0,4125,Riehen,Basel-Stadt,13580.0,2.0,2.0,0,0.0,2023-04-24,10010-12-31,NaN
581,582,Rolf,Ghouzlaoui,1953,1.0,8006,Zürich,Zürich,3467.0,1.0,2.0,0,0.0,2023-04-14,10010-12-31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11207,11208,Aissa,Stress,1993,2.0,8400,Winterthur,Zürich,13214.0,2.0,2.0,0,0.0,2023-04-30,2025-09-29,NaN
11208,11209,Ladan,Streuli,1993,2.0,8400,Winterthur,Zürich,17715.0,2.0,2.0,0,0.0,2023-04-23,2025-10-24,NaN
11209,11210,Andrea,Stroitz,1993,1.0,8636,Wald ZH,Zürich,1595.0,2.0,1.0,0,0.0,2023-05-03,10010-12-31,NaN
11210,11211,Nicole,Strunck,1996,1.0,1167,Lussy-sur-Morges,Vaud,15869.0,3.0,1.0,0,0.0,2023-05-08,10010-12-31,NaN
11211,11212,Lia,Stückelberger,1998,1.0,6600,Locarno,Ticino,14821.0,2.0,2.0,0,0.0,2023-04-14,10010-12-31,NaN